# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34b1e562e56e225f802a40d8c16a8b2c455213e29133bddab2187dde3105ba2f96b5eebf9143e3c2065ac83817756563047d6d98238236d5d02cbd3a4664a19b

test:
  secret_key_base: 77fbe8f3356fd8d10ffa77f9ee61c4ea82b6755ac4c9f80bad16d30b331e2e786b90e7cb57687c67878912b6c88298c857667605ff5398243201da6395e59b78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
